// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBetl5bPbB6a03FBIbQEYOxiz1cqJYbPJo',
    appId: '1:86749517535:web:cfa2e63a40951beae6bb6a',
    messagingSenderId: '86749517535',
    projectId: 'flash-chat-e1947',
    authDomain: 'flash-chat-e1947.firebaseapp.com',
    storageBucket: 'flash-chat-e1947.appspot.com',
    measurementId: 'G-XPEBC0FTX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE3F3gJdw_qk6ahB14nMZBbawr19kXXA4',
    appId: '1:86749517535:android:85e1bda2f862cfe9e6bb6a',
    messagingSenderId: '86749517535',
    projectId: 'flash-chat-e1947',
    storageBucket: 'flash-chat-e1947.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASO5GZ4TX_5dvmpVKHC5cXNuFt3HrZnpE',
    appId: '1:86749517535:ios:8b38edc709ec69b6e6bb6a',
    messagingSenderId: '86749517535',
    projectId: 'flash-chat-e1947',
    storageBucket: 'flash-chat-e1947.appspot.com',
    iosBundleId: 'com.abibdigit.flashChat',
  );

}